### ISSUE TITLE
[Suggestion] Support for command permissions

### ISSUE THREAD

**Issue by onepieceluffyy** [CalcWIZ16/ImageMapRenderer#2]
Great plugin, I like the simplicity and it works pretty well. One thing I’d like to request though. Could you add support for permissions?

**Comment by CalcWIZ16** [comment]
My apologies for the late reply, the most recent version of the plugin now has support for permissions. You can download it from this GitHub repository or Modrinth.
https://modrinth.com/plugin/imagemaprenderer
